name: Build & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & tag image
        run: |
          docker build \
            -t bhaktabhusandas/hello-devops-flask:latest \
            -t bhaktabhusandas/hello-devops-flask:${{ github.sha }} \
            .

      - name: Push images
        run: |
          docker push bhaktabhusandas/hello-devops-flask:latest
          docker push bhaktabhusandas/hello-devops-flask:${{ github.sha }}

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & update on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # Pull the image you just pushed
            docker pull bhaktabhusandas/hello-devops-flask:latest

            # Stop & remove old container
            docker stop hello-devops  || true
            docker rm   hello-devops  || true

            # Run new container
            docker run -d \
            --name hello-devops \
            -p 8080:8080 \
            bhaktabhusandas/hello-devops-flask:latest
